quarkus:
  datasource:
    devservices:
      enabled: true
    db-kind: mysql
  hibernate-orm:
    kotlin:
      database:
        generation: drop-and-create
      datasource: <default>
      packages: ac.me.entity.kotlin
"%dev":
  quarkus:
    banner:
      enabled: true
    hibernate-orm:
      log:
        sql: true
      cust:
        log:
          sql: true
"%prod":
  quarkus:
    banner:
      enabled: false
